version: '3.8'

services:
  db:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  config-server:
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "8888:8080"

  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8080:8080"

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8091:8080"

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    ports:
      - "8092:8080"

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8093:8083"